### PR TITLE
feat: define user controller

### LINKED ISSUE #6: Define UserController

### PR DESCRIPTION
**Pull request by Zish303**
Closes #6 

I have added controllers for User Authentication.
Includes:
1. Register
2. Login
3. Logout
4. JWT token generation
5. Stores user token in Redis

### CODE REVIEW

**Comment by professorabhay** [comment]
Need Fixes 
- Hash password before creating the user in DB 
- use bcrypt.compare method to check the password

**Comment by Zish303** [comment]
@professorabhay I have added password hashing using bcypt. I have also added a controller to change password.

**Comment by professorabhay** [comment]
LG!
- We are using ESM, so please update the "require" to "import"

**Comment by Zish303** [comment]
Done!

**Comment by professorabhay** [comment]
const { userId } = req.user;

change this also

**Comment by Zish303** [comment]
Done

**Comment by professorabhay** [comment]
Thanks @Zish303 💫

**Pull request merged**
